"""Stage 4: aggregate the ledgers into publishable tables (no email/answer text).

Reads ledger/questions.parquet, ledger/screen.parquet and, if present, ledger/semantic.parquet
(after `03_semantic_review.py collect`). Writes report/AGGREGATES.md and report/aggregates.json.
Coverage numbers are exact: semantic rows are counted from the collected reviews only.
"""
import json, sys
from pathlib import Path
import polars as pl
sys.path.insert(0, str(Path(__file__).parent))
from common import LEDGER, REPORT, questions

SPLITS = ["train", "dev", "test"]

def md_table(df: pl.DataFrame, floatfmt="{:.1f}") -> str:
    cols = df.columns
    lines = ["| " + " | ".join(cols) + " |", "|" + "|".join("---" for _ in cols) + "|"]
    for row in df.iter_rows():
        cells = []
        for v in row:
            if isinstance(v, float): cells.append(floatfmt.format(v))
            elif v is None: cells.append("")
            else: cells.append(str(v))
        lines.append("| " + " | ".join(cells) + " |")
    return "\n".join(lines)

def rate_table(df, cols, label):
    rows = []
    for c in cols:
        r = {"feature": c}
        for s in SPLITS:
            sub = df.filter(pl.col("split") == s)
            r[f"{s} n"] = int(sub[c].sum()); r[f"{s} %"] = 100 * float(sub[c].mean())
        r["all %"] = 100 * float(df[c].mean())
        rows.append(r)
    return md_table(pl.DataFrame(rows))

def main():
    q = questions().select("qid", "split", "user", "path", "include_email")
    sc = pl.read_parquet(LEDGER / "screen.parquet")
    df = q.join(sc, on="qid")
    agg = {"total_questions": df.height, "per_split": {s: int((df["split"] == s).sum()) for s in SPLITS}}
    out = ["# Aggregate tables (generated by `04_aggregate.py`)\n",
           f"Total questions: **{df.height:,}** (train {agg['per_split']['train']:,}, dev {agg['per_split']['dev']:,}, test {agg['per_split']['test']:,}). "
           "All rows below cover 100% of questions unless a section states its own coverage.\n"]

    # --- programmatic screening ---
    out.append("## A. Programmatic screening (surface features; 100% coverage)\n")
    out.append("### A1. Question form\n")
    qt = df.group_by("split", "q_type").len().pivot(on="split", index="q_type", values="len").fill_null(0)
    qt = qt.with_columns(total=pl.sum_horizontal(SPLITS)).with_columns((100 * pl.col("total") / df.height).alias("% all")).sort("total", descending=True)
    out.append(md_table(qt.select("q_type", *SPLITS, "total", "% all")))
    out.append("\n### A2. Gold-answer surface signals\n")
    out.append(rate_table(df, ["gold_yes_no", "gold_date_textual", "gold_date_numeric", "gold_year", "gold_time", "gold_money", "gold_percent",
                               "gold_email_addr", "gold_url", "gold_phone", "gold_quote", "gold_hedge", "q_according", "q_multi_wh"], "gold"))
    out.append("\n### A3. Evidence support of gold and alternate answers in the email text\n")
    df = df.with_columns((pl.col("gold_lcs_ratio") >= 0.8).alias("gold_lcs_ge_0.8"), (pl.col("gold_numbers_missing_from_email") > 0).alias("gold_number_missing_from_email"),
                         (pl.col("gold_caps_in_email_ratio") < 0.5).alias("gold_capitalized_tokens_mostly_absent"))
    out.append(rate_table(df, ["gold_verbatim_in_email", "gold_lcs_ge_0.8", "alt_verbatim_in_email", "alt_equals_gold", "gold_numbers_all_in_email",
                               "gold_number_missing_from_email", "gold_capitalized_tokens_mostly_absent"], "evidence"))
    out.append("\nGold length in words, quantiles (all splits): " + ", ".join(f"p{int(p*100)}={df['gold_words'].quantile(p):.0f}" for p in [0.1, 0.25, 0.5, 0.75, 0.9, 0.99]) + ".")
    out.append("Longest-common-substring share of gold covered verbatim by the email, quantiles: " + ", ".join(f"p{int(p*100)}={df['gold_lcs_ratio'].quantile(p):.2f}" for p in [0.1, 0.25, 0.5, 0.75, 0.9]) + ".\n")
    out.append("### A4. Supplied incorrect answers (MCQ distractor quality signals)\n")
    out.append(rate_table(df, ["inc_hedge_any", "inc_anachronism_any", "inc_shares_gold_numbers_any", "inc_any_in_email_lcs_gt_half"], "inc"))
    d = (df["inc_words_mean"] - df["gold_words"])
    out.append("\nDistractor length minus gold length (words), quantiles: " + ", ".join(f"p{int(p*100)}={d.quantile(p):+.0f}" for p in [0.1, 0.25, 0.5, 0.75, 0.9]) + ".\n")
    agg["screen"] = {c: {s: float(df.filter(pl.col("split") == s)[c].mean()) for s in SPLITS} for c in
                     ["gold_yes_no", "gold_date_textual", "gold_time", "gold_money", "gold_verbatim_in_email", "gold_lcs_ge_0.8", "q_according", "inc_hedge_any", "inc_anachronism_any"]}

    # --- semantic review ---
    sem_path = LEDGER / "semantic.parquet"
    if sem_path.exists():
        sem = pl.read_parquet(sem_path)
        j = df.join(sem, on="qid", how="inner")
        cov = {s: int((j["split"] == s).sum()) for s in SPLITS}
        cov_emails = j["path"].n_unique()
        agg["semantic"] = {"reviewed_questions": j.height, "reviewed_per_split": cov, "reviewed_emails": cov_emails,
                           "coverage_pct": 100 * j.height / df.height}
        out.append(f"## B. Item-level semantic review (Claude Fable, `claude -p`)\n")
        out.append(f"**Coverage: {j.height:,} of {df.height:,} questions ({100*j.height/df.height:.2f}%)**, from {cov_emails:,} of 73,772 emails; "
                   f"per split: train {cov['train']:,}/{agg['per_split']['train']:,}, dev {cov['dev']:,}/{agg['per_split']['dev']:,}, test {cov['test']:,}/{agg['per_split']['test']:,}. "
                   "Emails were processed in a fixed-seed shuffled order, so the reviewed set is a uniform sample of emails, not a hand-picked one. "
                   "Every percentage in this section is relative to the reviewed set only.\n")
        out.append("### B1. Verdict by split\n")
        v = j.group_by("split", "verdict").len().pivot(on="split", index="verdict", values="len").fill_null(0)
        v = v.with_columns(total=pl.sum_horizontal([c for c in SPLITS if c in v.columns])).with_columns((100 * pl.col("total") / j.height).alias("% reviewed")).sort("total", descending=True)
        out.append(md_table(v))
        out.append("\n### B2. Answer schema category by verdict\n")
        cv = j.group_by("cat", "verdict").len().pivot(on="verdict", index="cat", values="len").fill_null(0)
        vc = [c for c in ["convertible", "convertible_rewrite", "unconvertible"] if c in cv.columns]
        cv = cv.with_columns(total=pl.sum_horizontal(vc)).with_columns((100 * pl.col("total") / j.height).alias("% reviewed")).sort("total", descending=True)
        out.append(md_table(cv.select("cat", *vc, "total", "% reviewed")))
        out.append("\n### B3. Reviewer confidence by verdict\n")
        cf = j.group_by("verdict", "conf").len().pivot(on="conf", index="verdict", values="len").fill_null(0).sort("verdict")
        out.append(md_table(cf))
        out.append("\n### B4. Flags (share of reviewed items carrying each flag)\n")
        fl = j.select("qid", "verdict", "flags").explode("flags").drop_nulls("flags")
        ft = fl.group_by("flags").agg(pl.len().alias("n")).with_columns((100 * pl.col("n") / j.height).alias("% reviewed")).sort("n", descending=True)
        out.append(md_table(ft))
        out.append("\n### B5. Regex surface signal vs semantic category (does surface detection predict the schema?)\n")
        rows = []
        for feat, cats in [("gold_date_textual", ["date", "datetime"]), ("gold_date_numeric", ["date", "datetime"]), ("gold_time", ["time", "datetime"]),
                           ("gold_money", ["money"]), ("gold_percent", ["percent"]), ("gold_email_addr", ["email_addr"]), ("gold_yes_no", ["bool"]),
                           ("gold_verbatim_in_email", ["span"]), ("q_multi_wh", ["multi_field", "list"])]:
            pos = j.filter(pl.col(feat))
            hit = pos.filter(pl.col("cat").is_in(cats))
            catrows = j.filter(pl.col("cat").is_in(cats))
            rows.append({"surface feature": feat, "target cats": "/".join(cats), "feature fires": pos.height,
                         "precision % (fires -> cat)": 100 * hit.height / pos.height if pos.height else None,
                         "recall % (cat -> fires)": 100 * hit.height / catrows.height if catrows.height else None,
                         "fires but unconvertible %": 100 * (pos["verdict"] == "unconvertible").mean() if pos.height else None})
        out.append(md_table(pl.DataFrame(rows)))
        out.append("\n### B6. Verdict for question types\n")
        qv = j.group_by("q_type", "verdict").len().pivot(on="verdict", index="q_type", values="len").fill_null(0)
        qv = qv.with_columns(total=pl.sum_horizontal(vc)).with_columns((100 * pl.col("unconvertible") / pl.col("total")).alias("% unconvertible") if "unconvertible" in qv.columns else pl.lit(None).alias("% unconvertible")).sort("total", descending=True)
        out.append(md_table(qv))
        agg["semantic"]["verdict_counts"] = {r["verdict"]: int(r["total"]) for r in v.to_dicts()}
        agg["semantic"]["cat_counts"] = {r["cat"]: int(r["total"]) for r in cv.to_dicts()}
        agg["semantic"]["flag_counts"] = {r["flags"]: int(r["n"]) for r in ft.to_dicts()}
        agg["semantic"]["conf_counts"] = j.group_by("conf").len().to_dicts()
    else:
        out.append("## B. Item-level semantic review\n\nNot yet collected (`03_semantic_review.py collect`).\n")

    (REPORT / "AGGREGATES.md").write_text("\n".join(out) + "\n")
    json.dump(agg, open(REPORT / "aggregates.json", "w"), indent=1, default=str)
    print("\n".join(out)[:200]); print("... wrote", REPORT / "AGGREGATES.md")

if __name__ == "__main__":
    main()
